Repository projectsyn/component-steward, pull requests merged in 2025-01, with the labels that each got.

#88 Update quay.io/argoproj/argocd Docker tag to v2.13.3
  class/defaults.yml
  tests/golden/defaults/steward/steward/10_deployment.yaml
Labels: dependency, bump:patch, automerge

#86 Generate config map `additional-root-apps`
  .cruft.json
  .github/workflows/test.yaml
  .gitignore
  Makefile
  Makefile.vars.mk
  component/main.jsonnet
  jsonnetfile.jsonnet
  renovate.json
  tests/golden/defaults/steward/steward/20_additional_root_apps.yaml
  tests/golden/syn-teams/steward/apps/steward.yaml
  tests/golden/syn-teams/steward/steward/01_rbac.yaml
  tests/golden/syn-teams/steward/steward/05_secret.yaml
  tests/golden/syn-teams/steward/steward/10_deployment.yaml
  tests/golden/syn-teams/steward/steward/20_additional_facts.yaml
  tests/golden/syn-teams/steward/steward/20_additional_root_apps.yaml
  tests/syn-teams.yml
Labels: enhancement

#87 Update docker.io/projectsyn/steward Docker tag to v0.12.1
  class/defaults.yml
  tests/golden/defaults/steward/steward/10_deployment.yaml
  tests/golden/syn-teams/steward/steward/10_deployment.yaml
Labels: dependency, bump:minor

#89 Update quay.io/argoproj/argocd Docker tag to v2.13.4
  class/defaults.yml
  tests/golden/defaults/steward/steward/10_deployment.yaml
  tests/golden/syn-teams/steward/steward/10_deployment.yaml
Labels: dependency, bump:patch, automerge
